spring:
  application:
    name: "accounts"
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
#  config:
#    activate:
#      on-profile: "qa"

build:
  version: "2.0"

accounts:
  message: "Welcome to Accounts Service"
  contactDetails:
    name: "Karthik - Dev"
    email: "{cipher}c8018ec0bf53a61be5da00452fa49560ed3a5b6a4e14b0285e5793903f547b4b5766dd1622dabc800e0e0b818281ae96"
  onCallSupport:
   - (484) 555-1218
   - (484) 555-1219
