spring:
  application:
    name: "accounts"
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
#  config:
#    activate:
#      on-profile: "qa"

build:
  version: "2.0"

accounts:
  message: "Welcome to Accounts Service"
  contactDetails:
    name: "Karthik - Dev"
    email: "karthik@eazybytes.com"
  onCallSupport:
   - (484) 555-1218
   - (484) 555-1219
