spring:
  application:
    name: "accounts"
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
#  config:
#    activate:
#      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to Accounts Service"
  contactDetails:
    name: "Srikanth - Dev"
    email: "{cipher}986a151074ddbf87962be964a7241542f0561bcf17dcd18c54bca0619dadca9552117351cdeadeecd78cb6edcf5cce23"
  onCallSupport:
   - (484) 555-1210
   - (484) 555-1215
