spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  config:
    activate:
      on-profile: "prod"
build:
  version: "1.5"

cards:
  message: "Welcome to Cards Service - EazyBank"
  contactDetails:
    name: "Srikanth - Dev Lead"
    email: "srikanth@eazybytes.com"
  onCallSupport:
    - (484) 555-1218
    - (484) 555-1219
