server:
  port: 8090
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  config:
    activate:
      on-profile: prod

loans:
  message: "Welcome to Cards Service - EazyBank"
  contactDetails:
    name: "Karthik - Dev Lead"
    email: "kartik@eazybytes.com"
  onCallSupport:
    - (484) 555-1215
    - (484) 555-1216
